export const DASHBOARD_CONSTANTS = {
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",

  FETCH_POST_DETAILS: "FETCH_POST_DETAILS",
  FETCH_POST_DETAILS_SUCCESS: "FETCH_POST_DETAILS_SUCCESS",
  FETCH_POST_DETAILS_ERROR: "FETCH_POST_DETAILS_ERROR",

  RESET_POSTS: "RESET_POSTS",
  RESET_POST_DETAILS: "RESET_POST_DETAILS",
};
