export const LOGIN_CONSTANTS = {
  EMAIL: "EMAIL",
  PASSWORD: "PASSWORD",
  EMAIL_ERR: "EMAIL_ERR",
  PASSWORD_ERR: "PASSWORD_ERR",
  LOGIN_ERR: "LOGIN_ERR",
  RESET_LOGIN: "RESET_LOGIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};
