export const USER_DETAILS_CONSTANTS = {
  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",
  RESET_USER_DETAILS: "RESET_USER_DETAILS",
};
